#!/usr/bin/env python3
"""
VEX Anti-Cheat v2 — URL Encoder
Generate string.char() codes dari backend URL untuk VEX_BackendURL.lua
Jalankan: python3 VEX_URLEncoder.py
"""

def encode(url: str, xor_key: int = 0) -> str:
    if xor_key:
        codes = [str(ord(c) ^ xor_key) for c in url]
    else:
        codes = [str(ord(c)) for c in url]
    # Split per 8 chars for readability
    lines = []
    for i in range(0, len(codes), 8):
        chunk = url[i:i+8]
        line  = ", ".join(codes[i:i+8])
        lines.append(f"\t{line},  -- \"{chunk}\"")
    return "{\n" + "\n".join(lines) + "\n}"

def generate_lua(url: str, xor_key: int = 0) -> str:
    encoded = encode(url, xor_key)
    decode_fn = f"""
local function _r(t)
\tlocal s = ""
\tfor i = 1, #t do
\t\ts = s .. string.char({'bit32.bxor(t[i], ' + str(xor_key) + ')' if xor_key else 't[i]'})
\tend
\treturn s
end"""
    return f"""-- VEX_BackendURL.lua (Generated by VEX_URLEncoder.py)
-- ⚠️  Obfuscate file ini di https://luarmor.net sebelum publish!
-- URL: {url}
-- Mode: {'XOR key=' + str(xor_key) if xor_key else 'Plain'}
{decode_fn}

local _c = {encoded}

local RunService = game:GetService("RunService")
local function _get()
\tif RunService:IsClient() then
\t\terror("[VEX] Unauthorized!", 2)
\tend
\treturn _r(_c)
end

return {{ get = _get, Get = _get }}
"""

# ─── EDIT INI ────────────────────────────────────────────────
BACKEND_URL = "https://your-vex-backend.vercel.app"  # ← ganti
XOR_KEY     = 0  # 0 = plain, 1-255 = XOR (lebih aman)
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 55)
    print("  VEX Anti-Cheat — URL Encoder")
    print("=" * 55)
    print(f"\nURL    : {BACKEND_URL}")
    print(f"Length : {len(BACKEND_URL)} chars")
    print(f"Mode   : {'XOR key=' + str(XOR_KEY) if XOR_KEY else 'Plain'}\n")

    lua = generate_lua(BACKEND_URL, XOR_KEY)
    print(lua)

    out = "VEX_BackendURL_generated.lua"
    with open(out, "w") as f:
        f.write(lua)

    print(f"✅  Saved: {out}")
    print("   → Copy ke Roblox ModuleScript VEX_BackendURL")
    print("   → Lalu obfuscate di https://luarmor.net")
